# Generated by Django 6.0.5 on 2026-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_competitionrole_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="are_phase1_reviews_visible",
            field=models.BooleanField(
                default=False, verbose_name="Phase 1 reviews visible"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="are_phase2_reviews_visible",
            field=models.BooleanField(
                default=False, verbose_name="Phase 2 reviews visible"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="google_sheet_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Google Sheet URL"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="play_author_email_sheet_column_name",
            field=models.CharField(max_length=100, verbose_name="Author email column"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="play_author_first_name_sheet_column_name",
            field=models.CharField(
                max_length=100, verbose_name="Author first name column"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="play_author_last_name_sheet_column_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Author last name column",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="play_author_year_of_birth_sheet_column_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Author year of birth column",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="play_title_sheet_column_name",
            field=models.CharField(max_length=100, verbose_name="Play title column"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="play_url_sheet_column_name",
            field=models.CharField(max_length=100, verbose_name="Play URL column"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("setup", "Setup and Team Formation"),
                    ("phase_1", "Phase 1: Distribution (3 readers)"),
                    ("phase_2", "Phase 2: Open Reading"),
                    ("finished", "Finished"),
                ],
                default="setup",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
