# Generated by Django 6.0.5 on 2026-05-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0006_alter_competition_are_phase1_reviews_visible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="google_credentials",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
