# Generated by Django 6.0.5 on 2026-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Telegram"
            ),
        ),
    ]
