# Generated by Django 6.0.4 on 2026-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play",
            old_name="author_name",
            new_name="author_first_name",
        ),
        migrations.AddField(
            model_name="play",
            name="author_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
