# Generated by Django 6.0.4 on 2026-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_remove_play_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='author_year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
