# Generated by Django 6.0.5 on 2026-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0005_alter_play_author_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="internal_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
