# Generated by Django 6.0.5 on 2026-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0006_play_internal_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="force_phase_2",
            field=models.BooleanField(default=False),
        ),
    ]
