# Generated by Django 6.0.5 on 2026-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0007_play_force_phase_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="exclude_phase_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="phase_2_exclusion_comment",
            field=models.TextField(blank=True),
        ),
    ]
