# Generated by Django 6.0.5 on 2026-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_created_at_review_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("draft", "Draft"),
                    ("rejected", "Rejected"),
                    ("submitted", "Submitted"),
                ],
                max_length=20,
            ),
        ),
    ]
